### ISSUE TITLE
some more commands :)

### ISSUE THREAD

**Issue by d630** [izabera/clifix#1]
```sh
{a{dmin,l{ias,loc},pt{,-get,itude},r,sa,t,utoload,wk},b{a{s{ename,h},tch},c,g,ind{,key},reak,uiltin,ye},c{99,a{l{,ler},p,t},d,flow,h{dir,fn,grp,mod,own,sh},ksum,lone,mp,o{l,m{m{,and},p{arguments,c{all,tl},describe,files,g{en,roups},lete,opt,quote,ress,t{ags,ry},values}},ntinue,proc},p{,io},rontab,split,tags,u{rl,t},xref},d{ate,d,e{clare,lta},f,i{ff,r{name,s},s{able,own}},mesg,osh,u},e{cho{,t{c,i}},d,grep,macs,n{able,v},val,x{,ec,it,p{and,ort,r}}},f{alse,c,g{,rep},i{le,nd},o{ld,rt77},ree,user},g{e{ncat,t{,conf,opts,text}},it,r{ep,oup{add,del,mod,s}},unzip,zip},h{ash,e{ad,lp},g,ist{,ory},ostname,top},i{conv,d,fconfig,nstall{,_initd},p{c{rm,s},tables}},jo{bs,in},kill{,all},l{e{ss,t,x},ink,n,o{ca{l{,e{,def}},te},g{ger,in,name,out}},p{,r},s{,b_release}},m{4,a{ilx,ke,n,p{,file}},d5sum,esg,k{dir,fifo,nod,temp},o{re,unt},sgfmt,v},n{ano,ewgrp,ice,l,m,o{de,hup}},od,p{a{cman,s{swd,te},t{ch,hchk},x},erl,i{dof,ng},opd,r{,int{,f},s},s,ushd,wd,ython},q{alter,del,hold,m{ove,sg},r{erun,ls},s{elect,ig,tat,ub}},r{e{ad{,array,only},move_initd,nice,peat,turn},m{,d{el,ir}},pm},s{a{ct,vehistory},c{cs,p,reen},e{d,ndmail,t},h{,ift,opt,utdown},leep,o{rt,urce},plit,sh,t{op,ri{ngs,p},ty},u{,do,spend},vn,ync},t{a{bs,il,lk,r},e{e,st},ime{,s},mux,o{p,uch},put,r{,ap,ue},sort,ty,ype{,set}},u{limit,m{ask,ount},n{a{lias,me},compress,expand,get,iq,link,set},ser{add,del,mod},u{cp,decode,encode,stat,x}},v{al,i{,m}},w{ait,c,get,h{at,ence,ich,o},rite},xargs,y{acc,um},zcat}
```

**Comment by izabera** [comment]
hey thanks, i just wanted to ask: how did you generate the brace expression?
did you do it by hand or with a script?  if it's a script, does it always produce the shortest possible braceexp that expands to your text?

**Comment by d630** [comment]
hey, it's readlines' command "complete-into-braces"

**Comment by izabera** [comment]
aww, ok :cry: that's far from optimal
i'll add your commands, thanks

**Comment by izabera** [comment]
zsh stuff
--

- autoload
- bindkey
- bye
- cap
- chdir
- comparguments
- compcall
- compctl
- compdescribe
- compfiles
- compgroups
- compquote
- comptags
- comptry
- compvalues
- disable
- echotc
- echoti
- print
- repeat
- whence


sccs stuff
--

- admin
- cflow
- cxre
- delta
- get
- prs
- rmdel
- sact
- sccs
- unget
- val


posix batch jobs stuff
--

- qalter
- qdel
- qhold
- qmove
- qmsg
- qrerun
- qrls
- qselect
- qsig
- qstat
- qsub


misc posix obsolete stuff
--

- alloc
- asa
- compress
- fort77
- savehistory
- uncompress
- uucp
- uustat
- uux


idontevenknowwtf stuff
--

- dosh
- savehistory


keywords
--

- coproc
- time



this is either a joke or utter bs, and definitely a waste of time

thanks for your help, i'm not adding any of the above

besides, clifix will find a suitable command at runtime anyway, that list is just a way to speed up some common cases
